### PR TITLE
Typo

### PR DESCRIPTION
**Pull request by JordyCuan**
@nathanleclaire

### CODE REVIEW

**Comment by nathanleclaire** [comment]
Where exactly?

**Comment by JordyCuan** [comment]
I changed **and REST _endpionts_)** to this **and REST _endpoints_)**

**Comment by nathanleclaire** [comment]
Ah OK cool. Thanks! Github diff formatting wasn't picking up on that

**Comment by nathanleclaire** [comment]
LGTM

**Comment by JordyCuan** [comment]
Thanks to you

**Pull request merged**
