### PR TITLE
replaced redditService with userService in unit testing services post

### PR DESCRIPTION
**Pull request by Bairstow**

### CODE REVIEW

**Comment by nathanleclaire** [comment]
Nice.  There you go, submitting a PR is much appreciated!  It takes a village.

BTW, pinging me @nathanleclaire so I noticed would have been good... I just now noticed this

**Comment by nathanleclaire** [comment]
LGTM

**Comment by Bairstow** [comment]
no worries. i just came across your post recently and it helped me so thank you, and figured the change might help someone else too.

i'm a little new to all of this, had assumed that the pr would generate a notification, but will keep that in mind in the future.

**Comment by nathanleclaire** [comment]
> no worries. i just came across your post recently and it helped me so thank you, and figured the change might help someone else too.

Oh yeah a few people have been grousing about that :) So thanks for the fix

> i'm a little new to all of this, had assumed that the pr would generate a notification, but will keep that in mind in the future.

Yup depends on GH settings but since I get an overwhelming amount of email from GH I mostly rely on direct pings in my "notifications" tab on the website

**Pull request merged**
